apiVersion: v1
kind: Pod
metadata:
  name: secret-pod-type1
  namespace: default
  labels:
    app: secret-demo
    method: env-variable
spec:
  containers:
  - name: secret1
    image: nginx:alpine
    env:
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: my-app-secret
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-app-secret
          key: password
    - name: API_KEY
      valueFrom:
        secretKeyRef:
          name: my-app-secret
          key: api-key