apiVersion: v1
kind: Pod
metadata:
  name: secret-pod-type2
  namespace: default
  labels:
    app: secret-demo
    method: env-variable
spec:
  containers:
  - name: secret1
    image: nginx:alpine
    envFrom:
    - secretRef:
        name: my-app-secret