apiVersion: v1
kind: Pod
metadata:
  name: secret-pod-type3
  namespace: default
  labels:
    app: secret-demo
    method: env-variable
spec:
  containers:
  - name: secret1
    image: nginx:alpine

    volumeMounts:
      - name: secret-volume
        mountPath: /etc/secrets
        readOnly: true
  
  volumes:
  - name: secret-volume
    secret:
      secretName: my-app-secret
      defaultMode: 0400