apiVersion: v1
kind: Pod
metadata:
  name: my-calapp
  labels:
    name: my-calapp
spec:
  containers:
  - name: callapp
    image: thipparthiavinash/mycalapp-awar05
    ports:
    - containerPort: 80