apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2048-game-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: 2048-game
  template: 
    metadata:
      labels:
        app: 2048-game
    spec:
      containers:
      - name: 2048-game
        image: 982424467695.dkr.ecr.ap-south-1.amazonaws.com/game-2048-awar06:latest
        ports:
        - containerPort: 80