apiVersion: v1
kind: LimitRange
metadata:
  name: dev-limits
  namespace: dev-namespace
spec:
  limits:
    - default:
        cpu: "1"                #max CPU a container can get
        memory: "1Gi"           #max memory a container can get
      defaultRequest:
        cpu: "0.5"              #Default Requested CPU, if nothing defined in the manifest
        memory: "512Mi"         #Default Requested Memory, if nothing defined in the manifest
      type: Container