apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-collector
  namespace: default
spec:
  selector:
    matchLabels:
      app: log-col-daemon
  template: 
    metadata:
      labels:
        app: log-col-daemon
    spec:
      containers:
      - name: log-container
        image: nginx:latest
        ports:
          - containerPort: 80