apiVersion: v1
kind: Pod
metadata:
  name: 2048-secret-game
  labels:
    name: 2048-secret-game
spec:
  containers:
  - name: 2048game
    image: nginx
    command: [ "sh", "-c", "echo $DB_PASSWORD; sleep 300"]
    env:
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mydb-secret
            key: DB_PASSWORD