apiVersion: v1
kind: Pod
metadata:
  name: 2048-secret-game
  labels:
    name: 2048-secret-game
spec:
  containers:
  - name: 2048game
    image: nginx
    envFrom:
    - secretRef:
        name: db-secret