apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::982424467695:role/eksctl-ekswithavinash-addon-iamserviceaccount-Role1-J5aCrtD4rzUr